#include <cdps/bridge.h>
#include <cdps/chain_of_responsibility.h>
#include <cdps/decorator.h>
#include <cdps/facade.h>
#include <cdps/factory.h>
#include <cdps/observer.h>
#include <cdps/singleton.h>
#include <cdps/version.h>
#include <cdps/visitor.h>
