#include <cdps/adapter.h>
#include <cdps/bridge.h>
#include <cdps/builder.h>
#include <cdps/chain_of_responsibility.h>
#include <cdps/composite.h>
#include <cdps/decorator.h>
#include <cdps/facade.h>
#include <cdps/factory.h>
#include <cdps/fly_weight.h>
#include <cdps/observer.h>
#include <cdps/prototype.h>
#include <cdps/proxy.h>
#include <cdps/singleton.h>
#include <cdps/version.h>
#include <cdps/visitor.h>
